[default]
cdap_host=127.0.0.1
cdap_user=cdap
cdap_password=xxxxxxxx
pipelines_list_path=/home/demo/project/exported_pipelines/default

[datafusion]
project-id=project-test-276409
location=asia-east2
instance-id=project-datafusion-test